export const ADD_EVIDENCE_REQUEST = 'FACTLIST/ADD_EVIDENCE_REQUEST'
export const ADD_EVIDENCE_SUCCESS = 'FACTLIST/ADD_EVIDENCE_SUCCESS'
export const ADD_EVIDENCE_FAILURE = 'FACTLIST/ADD_EVIDENCE_FAILURE'
