export const SIGN_IN_REQUEST = 'FACLIST/SIGN_IN_REQUEST'
export const SIGN_IN_SUCCESS = 'FACTLIST/SIGN_IN_SUCCESS'
export const SIGN_IN_FAILURE = 'FACTLIST/SIGN_IN_FAILURE'

export const SIGN_OUT_REQUEST = 'FACTLIST/SIGN_OUT_REQUEST'
export const SIGN_OUT_SUCCESS = 'FACTLIST/SIGN_OUT_SUCCESS'
export const SIGN_OUT_FAILURE = 'FACTLIST/SIGN_OUT_FAILURE'
