export const SIGN_UP_REQUEST = 'FACTLIST/SIGN_UP_REQUEST'
export const SIGN_UP_SUCCESS = 'FACTLIST/SIGN_UP_SUCCESS'
export const SIGN_UP_FAILURE = 'FACTLIST/SIGN_UP_FAILURE'

export const SIGN_UP_FORM_NAME = 'FACTLIST/SIGN_UP_FORM'
export const UPDATE_USER_FORM_NAME = 'FACTLIST/UPDATE_USER_FORM'

export const UPDATE_USER_REQUEST = 'FACTLIST/UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'FACTLIST/UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILURE = 'FACTLIST/UPDATE_USER_FAILURE'

export const FETCH_USER_REQUEST = 'FACTLIST/FETCH_USER_REQUEST'
export const FETCH_USER_SUCCESS = 'FACTLIST/FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FACTLIST/FETCH_USER_FAILURE'
