export const FETCH_EMBED_REQUEST = 'FACTLIST/FETCH_EMBED_REQUEST'
export const FETCH_EMBED_SUCCESS = 'FACTLIST/FETCH_EMBED_SUCCESS'
export const FETCH_EMBED_FAILURE = 'FACTLIST/FETCH_EMBED_FAILURE'
export const REMOVE_EMBED = 'FACTLIST/REMOVE_EMBED'
