export const FETCH_EMBED_REQUEST = 'FACTLIST/FETCH_EMBED_REQUEST'
export const FETCH_EMBED_SUCCESS = 'FACTLIST/FETCH_EMBED_SUCCESS'
export const FETCH_EMBED_FAILURE = 'FACTLIST/FETCH_EMBED_FAILURE'

export const EMBED_REMOVE = 'FACTLIST/EMBED_REMOVE'

export const RESET_EVIDENCE_EMBEDS = 'FACTLIST/RESET_EVIDENCE_EMBEDS'
export const RESET_CLAIM_EMBEDS = 'FACTLIST/RESET_CLAIM_EMBEDS'
