export const FETCH_CLAIMS_REQUEST = 'CLAIMS/FETCH_REQUEST'
export const FETCH_CLAIMS_SUCCESS = 'CLAIMS/FETCH_SUCCESS'
export const FETCH_CLAIMS_FAILURE = 'CLAIMS/FETCH_FAILURE'

export const ADD_CLAIM_REQUEST = 'CLAIMS/ADD_REQUEST'
export const ADD_CLAIM_SUCCESS = 'CLAIMS/ADD_SUCCESS'
export const ADD_CLAIM_FAILURE = 'CLAIMS/ADD_FAILURE'
