export const FETCH_CLAIMS_REQUEST = 'FETCH_CLAIMS_REQUEST'
export const FETCH_CLAIMS_SUCCESS = 'FETCH_CLAIMS_SUCCESS'
export const FETCH_CLAIMS_FAILURE = 'FETCH_CLAIMS_FAILURE'

export const FETCH_CLAIM_BY_ID_REQUEST = 'FETCH_CLAIM_BY_ID_REQUEST'
export const FETCH_CLAIM_BY_ID_SUCCESS = 'FETCH_CLAIM_BY_ID_SUCCESS'
export const FETCH_CLAIM_BY_ID_FAILURE = 'FETCH_CLAIM_BY_ID_FAILURE'

export const ADD_CLAIM_FORM = 'ADD_CLAIM_FORM'
export const ADD_CLAIM_REQUEST = 'ADD_CLAIM_REQUEST'
export const ADD_CLAIM_SUCCESS = 'ADD_CLAIM_SUCCESS'
export const ADD_CLAIM_FAILURE = 'ADD_CLAIM_FAILURE'
export const RESET_ADD_CLAIM_STATES = 'RESET_ADD_CLAIM_STATES'
