export const FETCH_ALL_CLAIMS_REQUEST = 'CLAIM/FETCH_ALL_REQUEST'
export const FETCH_ALL_CLAIMS_SUCCESS = 'CLAIM/FETCH_ALL_SUCCESS'
export const FETCH_ALL_CLAIMS_FAILURE = 'CLAIM/FETCH_ALL_FAILURE'

export const FETCH_CLAIM_REQUEST = 'CLAIM/FETCH_REQUEST'
export const FETCH_CLAIM_SUCCESS = 'CLAIM/FETCH_SUCCESS'
export const FETCH_CLAIM_FAILURE = 'CLAIM/FETCH_FAILURE'

export const ADD_CLAIM_REQUEST = 'CLAIM/ADD_REQUEST'
export const ADD_CLAIM_SUCCESS = 'CLAIM/ADD_SUCCESS'
export const ADD_CLAIM_FAILURE = 'CLAIM/ADD_FAILURE'
export const RESET_ADD_CLAIM_STATES = 'CLAIM/RESET_ADD_CLAIM'

export const CLAIM_FORM = 'FACTLIST/CLAIM_FORM'
