export const FILE_UPLOAD_REQUEST = 'FACTLIST/FILE_UPLOAD_REQUEST'
export const FILE_UPLOAD_SUCCESS = 'FACTLIST/FILE_UPLOAD_SUCCESS'
export const FILE_UPLOAD_FAILURE = 'FACTLIST/FILE_UPLOAD_FAILURE'
export const REMOVE_FILE_REQUEST = 'FACTLIST/REMOVE_FILE_REQUEST'
