export const FETCH_TOPICS_REQUEST = 'FETCH_TOPICS_REQUEST'
export const FETCH_TOPICS_SUCCESS = 'FETCH_TOPICS_SUCCESS'
export const FETCH_TOPICS_FAILURE = 'FETCH_TOPICs_FAILURE'

export const UPDATE_TOPIC_TITLE = 'UPDATE_TOPIC_TITLE'
