export const SHOW_MODAL = 'FACTLIST/MODALS/SHOW'
export const HIDE_MODAL = 'FACTLIST/MODALS/HIDE'

// Available modal constants
export const SIGN_IN_MODAL = 'FACTLIST/MODALS/SIGN_IN'
export const SIGN_UP_MODAL = 'FACTLIST/MODALS/SIGN_UP'
export const PASSWORD_RESET_MODAL = 'FACTLIST/PASSWORD_RESET_MODAL'
export const IMAGE_MODAL = 'FACTLIST/IMAGE_MODAL'
